# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d67dc8c700e0cdb7f6e2dea4330f73df954d963d88ca3418d1c8c1887106c75b2efdfba98796f1a475707fbb840df704c0fa99673c3b87f10f6dd4148dca4ec

test:
  secret_key_base: a890dc007ff7e798d6c7fa84bf6e3af94c078b1fb1bdfe18b9a74e4a812cb6778adc858c30d7af7337dcfd6dc09eb496bd0bb2f8964398caa888bd88fcb3f7d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
